language: python
cache: pip
sudo: false

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6

# Whitelist
# gh-pages is otherwise ignored by Travis CI
# Use a regex to whitelist gh-pages and all branches
branches:
  only:
    - gh-pages
    - /.*/

install:
 - pip install -U pip
 - pip install -U black flake8
 - pip install -U -r requirements.txt

script:
 # Static analysis
 - flake8 --statistics --count
 - black --check --diff .

 # Test run
 - python xdaysofxmasbot.py --help
 - python xdaysofxmasbot.py --test --yaml xdaysofxmasbot_example.yaml
